first draft
kfirbio/GeoDB pull request #1
Opened 2023-02-22 09:19 UTC by kfirbio

2023-02-26 15:34 UTC, asafalon1 requested changes

2023-02-26 15:34 UTC, asafalon1 commented on pyproject.toml
> +uvicorn = {extras = ["standard"], version = "^0.20.0"}
why the extras=standard? what does that do?

2023-02-26 15:34 UTC, asafalon1 commented on pyproject.toml
> +mypy = "^1.0.1"
you dont want to install pytest or mypy when you deploy your service, only when you run and test it locally. (hint - poetry supports the feature you are looking for ;) )

2023-02-26 15:34 UTC, asafalon1 commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
do you need this? what does this do?

2023-02-26 15:34 UTC, asafalon1 commented on scripts/lint.sh
> +python -m isort . -c
isort should also use max lines of 120 characters like flake8, otherwise they will fail each other.

2023-02-26 15:34 UTC, asafalon1 commented on scripts/lint.sh
> +python3 -m mypy --explicit-package-bases --show-error-codes GeoDB
why --explicit-package-bases? or --show-error-codes? what do these options do? and why do you need them?

2023-02-26 15:34 UTC, asafalon1 commented on scripts/lint.sh
> +python3 -m mypy --explicit-package-bases --show-error-codes GeoDB
seems like you do a lot of configuring using CLI args, is there another method to do this?

2023-02-26 15:34 UTC, asafalon1 commented on tests/unittests/geo.py
> +    assert res.city == "sidney2"
add more test cases - the max ip in the range, one in between etc.

2023-02-26 15:34 UTC, asafalon1 commented on tests/unittests/geo.py
> +        geo_data.calc_geo_data("121.21.21.21")
testing you get not found when the DB is empty is an edge case, you forgot to test the real case - out of range ip.

2023-02-26 15:34 UTC, asafalon1 commented on tests/unittests/geo.py
> +        geo_data.calc_geo_data("no valid")
test more invalid cases?

2023-02-27 08:43 UTC, kfirbio commented on .github/workflows/test.yml
> +          ${{ runner.os }}-pip-
dependencies caching, it should saves the time for fetching the dependencies again and again each build

2023-02-27 08:52 UTC, kfirbio commented on GeoDB/main.py
> +def read_root():
opps that was the default function on the fastapi template, changed to get_health_status

2023-02-27 09:21 UTC, kfirbio commented on GeoDB/main.py
> +    GeoDataLibInstance = GeoDataLib()
done

2023-02-27 09:22 UTC, kfirbio commented on GeoDB/main.py
> +        return res
done

2023-02-27 09:34 UTC, kfirbio commented on GeoDB/core/geo_data_lib.py
> +    def calc_geo_data(self, input: str) -> GeoDataResponse:
done

2023-02-27 09:55 UTC, kfirbio commented on GeoDB/core/geo_data_lib.py
> +        },
done

2023-02-27 09:55 UTC, kfirbio commented on GeoDB/core/geo_data_lib.py
> +    _db: List[Any] = [
done

2023-02-27 10:06 UTC, kfirbio commented on GeoDB/schemas/api.py
> +        self.city = city
done

2023-02-27 11:11 UTC, kfirbio commented on pyproject.toml
> +uvicorn = {extras = ["standard"], version = "^0.20.0"}
more dependencies which not actually used, removing

2023-02-27 11:20 UTC, kfirbio commented on tests/unittests/geo.py
> +    assert res.city == "sidney2"
done

2023-02-27 12:33 UTC, kfirbio commented on scripts/lint.sh
> +python3 -m mypy --explicit-package-bases --show-error-codes GeoDB
avoid placing __init__ anywhere

2023-02-27 12:33 UTC, kfirbio commented on scripts/lint.sh
> +python3 -m mypy --explicit-package-bases --show-error-codes GeoDB
moved to setup.cfg

2023-02-27 12:51 UTC, kfirbio commented on Dockerfile
> +ENV PYTHONOPTIMIZE=1
PYTHONOPTIMIZE - optimizing for prod (debug off. no asserts)
PYTHONPATH - python lib locations, setting it to the main app path

2023-02-27 13:05 UTC, kfirbio commented on Dockerfile
> +RUN cd /tmp && poetry install --no-dev --no-root
--no-dev for removing dev related libs (tests,lints) 
--no-root is for avoiding packing the root package as dependency

2023-02-27 13:06 UTC, kfirbio commented on .github/workflows/test.yml
> +        poetry install --no-root
to avoid packing the main package as dependency (same as dockerfile)

2023-02-27 13:57 UTC, kfirbio commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
this is for fixing poetry to manage python build. can be alter to different manager but not totally removed

2023-02-28 12:59 UTC, asafalon1 requested changes

2023-02-28 12:59 UTC, asafalon1 commented on pyproject.toml
> +yellowbox = "^0.8.2"
yellowbox should be a dev dependency

2023-02-28 12:59 UTC, asafalon1 commented on pyproject.toml
> +pytest-asyncio = "^0.20.3"
pytest should be a dev dependency

2023-02-28 12:59 UTC, asafalon1 commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
I just removed it from one of my services and it works fine, are you sure you cant remove it?

2023-02-28 12:59 UTC, asafalon1 commented on tests/blackox/test_app.py
> +import pytest
folder name is blackox 😆

2023-02-28 12:59 UTC, asafalon1 commented on tests/blackox/test_app.py
> +    async with TestClient(app) as client:
why dont you make a single fixture for the test client that has a higher scope?
if you had a thousand tests it will take forever to run if you create the client every time.

2023-02-28 12:59 UTC, asafalon1 commented on tests/unittests/geo.py
> +        geo_data.calc_geo_data("999.999.999.999")
pytest lets you do this more easily with a decorator called parameterize. look it up.

2023-03-01 08:33 UTC, asafalon1 approved these changes

2023-03-01 11:10 UTC, merged